### ISSUE TITLE
Writing Contribution Guidelines 

### ISSUE THREAD

**Issue by SaicharanKandukuri** [GDSCParulUniversity/.github#3]
> **Contribution Guidelines** guidelines file helps project contributors to do the work, file defined at `<project_root>/CONTRIBUTING.md`

## Task:
- [x] #4
- [ ] #5
- [x] #6
- [x] #7
- [ ] #8

## Also
- Structure guide
- use emojis & Gifs ( for good readability )

<hr>

> 💡 for better markdown structure use markdown lint
> *vscode*:  [Marketplace install](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)

> Anyone is welcome to contribute to these tasks
> make changes only in the Development branch

**Comment by SaicharanKandukuri** [comment]
> for reference: 
https://github.com/atom/atom/blob/master/CONTRIBUTING.md 
https://github.com/rails/rails/blob/main/CONTRIBUTING.md

**Comment by SaicharanKandukuri** [comment]
Ill take care of 1'st task

**Comment by AnninoDr4** [comment]
Nice Readme by the way 👏
> 👌
